### PR TITLE
Fix errors associaed with trying to use vector multiply word on P7.

### LINKED ISSUE #82: Some files are missing -mcpu
Some C files make usage of POWER8 built-ins without passing `-mcpu=power8`
to the compiler, e.g.:
```
In file included from src/pveclib/vec_int64_ppc.h:26,
                 from src/pveclib/vec_int128_ppc.h:28,
                 from src/tipowof10.c:23:
src/pveclib/vec_int32_ppc.h: In function ‘vec_mulesw’:
src/pveclib/vec_int32_ppc.h:736:3: note: builtin ‘__builtin_vec_mule’ requires builtin ‘__builtin_altivec_vmulesw’
  736 |   res = vec_mule (a, b);
      |   ^~~
```

This works well on powerpc64le because GCC defaults to `-mcpu=power8`.
However, when building for powerpc64, GCC defaults to `-mcpu=power4`, causing these errors.

I've noticed this with the following files:
 - src/testsuite/vec_int128_dummy.c
 - src/tipowof10.c
 - src/testsuite/vec_int64_dummy.c

### PR DESCRIPTION
**Pull request by munroesj52**
Fixes #82
Initially this was from missing multiply signed word implementation
for P7. But also hit a compiler bug where some built-ins where disabled
when I mixed -mcpu= and #pragma GCC target with different targets.
Specifically -mcpu=power7 and #pragma GCC target ("cpu=power8").
This seems to be Endian specific as P7 is BE only while P8 can be
either. Anyway. compiler folks are busy and will not spend cycles on a
bug that only impacts P7. So I added not conditionals to avoid this.
This should resolve issue #82.

	* src/pveclib/vec_f64_ppc.h (vec_all_isfinitef64,
	vec_all_isinff64, vec_all_isnanf64, vec_all_isnormalf64,
	vec_all_issubnormalf64, vec_all_iszerof64
	[__ORDER_LITTLE_ENDIAN__]): Test data built-ins only available
	for LE.

	* src/pveclib/vec_int128_ppc.h (vec_cmpsq_all_eq,
	vec_cmpsq_all_ne, vec_cmpuq_all_eq, vec_cmpuq_all_ne
	[__ORDER_LITTLE_ENDIAN__]):
	Generic vec_all_eq() for vector long only available for LE.

	* src/pveclib/vec_int32_ppc.h
	(vec_muleuw, vec_mulouw, vec_srawi): Forward reference.
	(vec_mulesw, vec_mulosw):
	Additional doxygent text.
	(vec_mulesw, vec_mulosw[! _ARCH_PWR8]):
	New implementation for POWER7
	(vec_muleuw, vec_mulouw):
	Additional doxygent text.

	* src/pveclib/vec_int64_ppc.h
	(vec_cmpsd_all_eq, vec_cmpsd_all_gt, vec_cmpsd_all_ne,
	vec_cmpsd_any_eq, vec_cmpsd_any_ge, vec_cmpsd_any_gt,
	vec_cmpsd_any_ne, vec_cmpud_all_eq, vec_cmpud_all_ge,
	vec_cmpud_all_gt, vec_cmpud_all_ne, vec_cmpud_any_eq,
	vec_cmpud_any_ge, vec_cmpud_any_gt, vec_cmpud_any_ne
	[__ORDER_LITTLE_ENDIAN__]):
	Generic vec_[all|any]_[eq|gt|ge|ne]() for vector long only
	available for LE.

	* src/testsuite/arith128_print.h (check_v2b64x):
	Use vec_cmpud_any_ne.
	* src/testsuite/arith128_test_i32.c (test_mulesw, test_mulosw):
	New functions.
	(test_muleuw): Add calls to test_mulesw and test_mulosw.

	* src/testsuite/vec_f32_dummy.c [defined vec_float2  &&
	(__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)]:
	Restrict float* built-in compile tests to LE.

	* src/testsuite/vec_int32_dummy.c (__test_mulesw,
	__test_mulosw, __test_abssw, __test_mullsw): New functions.

	* src/testsuite/vec_int64_dummy.c
	[(__GNUC__ > 7)  && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)]:
	Restrict merge even/odd built-in compile tests to LE.

	* src/testsuite/vec_pwr9_dummy.c (vec_all_isfinitef64,
	vec_all_isinff64, vec_all_isnanf64, vec_all_isnormalf64,
	vec_all_issubnormalf64, vec_all_iszerof64
	[__ORDER_LITTLE_ENDIAN__]): Test data built-ins only available
	for LE.

Signed-off-by: Steven Munroe <munroesj52@gmail.com>

### CODE REVIEW

**Comment by ThinkOpenly** [comment]
If you use the text `Fixes #82` in your commit message, that issue will be closed when this pull request is merged, just FYI.

File: src/pveclib/vec_int32_ppc.h [hunk 1]
```diff
@@ -789,6 +876,17 @@ vec_mulosw (vi32_t a, vi32_t b)
  * Multiple the even words of two vector unsigned int values and return
  * the unsigned long product of the even words.
  *
+ * For POWER8 and later we can use the vmuleuw instruction.
+ * But for POWER7 and earlier we have to construct word multiplies
+ * from two halfword multiplies (vmuleuh and vmulouh). Then sum the
+ * partial products for the final doubleword results. This is
+ * complicated the fact that vector add doubleword is not available
```
Comment (ThinkOpenly) [inline src/pveclib/vec_int32_ppc.h]: complicated _by_ the fact...

File: src/pveclib/vec_int32_ppc.h [hunk 2]
```diff
@@ -789,6 +876,17 @@ vec_mulosw (vi32_t a, vi32_t b)
...
+ * for POWER7. So we need to construct the doubleword add from
+ * Vector Add Unsigned Word Modulo (vadduwm) and
+ * Vector Add and Write Carry-Out Unsigned Word (vaddcuw) with
+ * shift double quadword to reposition the low word carry and
+ * a final vadduwm to complete carry propagation the doubleword add.
```
Comment (ThinkOpenly) [inline src/pveclib/vec_int32_ppc.h]: ...to complete _the_ carry propagation _for_ the doubleword add.  ?

File: src/pveclib/vec_int32_ppc.h [hunk 3]
```diff
@@ -880,6 +978,17 @@ vec_muleuw (vui32_t a, vui32_t b)
  * Multiple the odd words of two vector unsigned int values and return
  * the unsigned long product of the odd words.
  *
+ * For POWER8 and later we can use the vmulouw instruction.
+ * But for POWER7 and earlier we have to construct word multiplies
+ * from two halfword multiplies (vmuleuh and vmulouh). Then sum the
+ * partial products for the final doubleword results. This is
+ * complicated the fact that vector add doubleword is not available
```
Comment (ThinkOpenly) [inline src/pveclib/vec_int32_ppc.h]: ...complicated _by_ the fact...

File: src/pveclib/vec_int32_ppc.h [hunk 4]
```diff
@@ -880,6 +978,17 @@ vec_muleuw (vui32_t a, vui32_t b)
...
+ * for POWER7. So we need to construct the doubleword add from
+ * Vector Add Unsigned Word Modulo (vadduwm) and
+ * Vector Add and Write Carry-Out Unsigned Word (vaddcuw) with
+ * shift double quadword to reposition the low word carry and
+ * a final vadduwm to complete carry propagation the doubleword add.
```
Comment (ThinkOpenly) [inline src/pveclib/vec_int32_ppc.h]: ...complete _the_ carry propagation _for_ the doublework add. ?

File: src/pveclib/vec_int32_ppc.h (hunk 1 above)
Comment (munroesj52) [reply src/pveclib/vec_int32_ppc.h]: Ok

File: src/pveclib/vec_int32_ppc.h (hunk 2 above)
Comment (munroesj52) [reply src/pveclib/vec_int32_ppc.h]: Ok

File: src/pveclib/vec_int32_ppc.h (hunk 3 above)
Comment (munroesj52) [reply src/pveclib/vec_int32_ppc.h]: Ok

File: src/pveclib/vec_int32_ppc.h (hunk 4 above)
Comment (munroesj52) [reply src/pveclib/vec_int32_ppc.h]: Ok
